M48
; DRILL file KiCad 10.0.6-10.0.6~ubuntu26.04.1 date 2026-09-05T15:40:43
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-05T15:40:43+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6-10.0.6~ubuntu26.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X153.72Y-99.97
X153.72Y-105.75
M30
